// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project e9fcd0079d4f7d10 "AEO Analitycs", do not edit manually */
"use client";

// virtual:header
/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * labels?: { menu: string, close: string, items: { label: string, href: string }[] }
}} Props

 */
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cyKnXB8mh1xD50Qkgb1Z/KV29J4pbZWocE04wJNbP/aQpj0WMWY.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
import Link from "next/link";
var cycleOrder = ["u1JEICRqw", "Z5ukl7fmw"];
var serializationHash = "framer-vMfWh";
var variantClassNames = {
	u1JEICRqw: "framer-v-u8ibv2",
	Z5ukl7fmw: "framer-v-1rfli15",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Variant 1": "u1JEICRqw",
	"Variant 2": "Z5ukl7fmw",
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "u1JEICRqw",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, labels: labelsProp, ...restProps } = getProps(props);
	const labels = labelsProp ?? {
		menu: "Menu",
		close: "Close",
		items: [
			{ label: "R\xD3LUNK", href: "/" },
			{ label: "ESEM\xC9NYEK", href: "/events" },
			{ label: "EL\u0150AD\xD3K", href: "/#lineup" },
			{ label: "H\xCDREK", href: "/my-tickets" },
		],
	};
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "u1JEICRqw",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTapqy13ya = activeVariantCallback(async (...args) => {
		setVariant("Z5ukl7fmw");
	});
	const onTap1x3tutn = activeVariantCallback(async (...args) => {
		setVariant("u1JEICRqw");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "Z5ukl7fmw") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-u8ibv2",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"u1JEICRqw"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(255, 255, 255, 0.13)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(30px)",
							backgroundColor: "rgba(0, 0, 0, 1)",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							WebkitBackdropFilter: "blur(30px)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								Z5ukl7fmw: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							suppressHydrationWarning={true}
							className={"framer-1jq0t8w"}
							layoutDependency={layoutDependency}
							layoutId={"wUIACUwMV"}
							transformTemplate={transformTemplate1}
							{...addPropertyOverrides(
								{
									Z5ukl7fmw: {
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<img
									src="/logo.svg"
									alt="Bass Piknik"
									className={"framer-8vf0da"}
									style={{ height: 20, width: "auto", objectFit: "contain" }}
								/>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-lugj6d"}
								data-border={true}
								data-highlight={true}
								layoutDependency={layoutDependency}
								layoutId={"zk8PnVbJV"}
								onTap={onTapqy13ya}
								style={{
									"--border-bottom-width": "1px",
									"--border-color": "rgba(255, 255, 255, 0.15)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backdropFilter: "blur(10px)",
									backgroundColor: "rgba(255, 255, 255, 0.08)",
									borderBottomLeftRadius: 23,
									borderBottomRightRadius: 23,
									borderTopLeftRadius: 23,
									borderTopRightRadius: 23,
									WebkitBackdropFilter: "blur(10px)",
								}}
								{...addPropertyOverrides(
									{
										Z5ukl7fmw: {
											onTap: onTap1x3tutn,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1iqy00d"}
									fonts={["GF;Funnel Display-regular"]}
									layoutDependency={layoutDependency}
									layoutId={"OIIp_3u2r"}
									style={{
										"--extracted-r6o4lv": "rgb(255, 255, 255)",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											Z5ukl7fmw: {
												children: (
													<React.Fragment>
														<motion.p
															suppressHydrationWarning={true}
															style={{
																"--font-selector":
																	"R0Y7RnVubmVsIERpc3BsYXktcmVndWxhcg==",
																"--framer-font-family":
																	'var(--font-geist-sans), sans-serif',
																"--framer-font-size": "15px",
																"--framer-text-alignment": "center",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, rgb(255, 255, 255))",
															}}
														>
															{labels.close}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											suppressHydrationWarning={true}
											style={{
												"--font-selector":
													"R0Y7RnVubmVsIERpc3BsYXktcmVndWxhcg==",
												"--framer-font-family": 'var(--font-geist-sans), sans-serif',
												"--framer-font-size": "15px",
												"--framer-text-alignment": "center",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgb(255, 255, 255))",
											}}
										>
											{baseVariant === "Z5ukl7fmw" ? labels.close : labels.menu}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-1ou1rhh"}
								layoutDependency={layoutDependency}
								layoutId={"g1ZyIu0Nj"}
							>
								{isDisplayed() && (
									<Link href={labels.items[0].href} onClick={onTap1x3tutn} style={{ display: "contents" }}><RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1ft3hw2"}
										fonts={["GF;Funnel Display-800"]}
										layoutDependency={layoutDependency}
										layoutId={"jL5EkArc_"}
										style={{
											"--extracted-r6o4lv": "rgb(117, 117, 117)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector": "R0Y7RnVubmVsIERpc3BsYXktODAw",
													"--framer-font-family":
														'var(--font-geist-sans), sans-serif',
													"--framer-font-size": "38px",
													"--framer-font-weight": "800",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(117, 117, 117))",
												}}
											>
												{labels.items[0].label}
											</motion.p>
										</React.Fragment>
									</RichText></Link>
								)}
								{isDisplayed() && (
									<Link href={labels.items[1].href} onClick={onTap1x3tutn} style={{ display: "contents" }}><RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1tt2cf6"}
										fonts={["GF;Funnel Display-800"]}
										layoutDependency={layoutDependency}
										layoutId={"cxjfMVa1V"}
										style={{
											"--extracted-r6o4lv": "rgb(117, 117, 117)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector": "R0Y7RnVubmVsIERpc3BsYXktODAw",
													"--framer-font-family":
														'var(--font-geist-sans), sans-serif',
													"--framer-font-size": "38px",
													"--framer-font-weight": "800",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(117, 117, 117))",
												}}
											>
												{labels.items[1].label}
											</motion.p>
										</React.Fragment>
									</RichText></Link>
								)}
								{isDisplayed() && (
									<Link href={labels.items[2].href} onClick={onTap1x3tutn} style={{ display: "contents" }}><RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1ewb01i"}
										fonts={["GF;Funnel Display-800"]}
										layoutDependency={layoutDependency}
										layoutId={"XLyr8YTQl"}
										style={{
											"--extracted-r6o4lv": "rgb(117, 117, 117)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector": "R0Y7RnVubmVsIERpc3BsYXktODAw",
													"--framer-font-family":
														'var(--font-geist-sans), sans-serif',
													"--framer-font-size": "38px",
													"--framer-font-weight": "800",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(117, 117, 117))",
												}}
											>
												{labels.items[2].label}
											</motion.p>
										</React.Fragment>
									</RichText></Link>
								)}
								{isDisplayed() && (
									<Link href={labels.items[3].href} onClick={onTap1x3tutn} style={{ display: "contents" }}><RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-18js542"}
										fonts={["GF;Funnel Display-800"]}
										layoutDependency={layoutDependency}
										layoutId={"LfccBODBP"}
										style={{
											"--extracted-r6o4lv": "rgb(117, 117, 117)",
											"--framer-link-text-color": "rgb(0, 153, 255)",
											"--framer-link-text-decoration": "underline",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector": "R0Y7RnVubmVsIERpc3BsYXktODAw",
													"--framer-font-family":
														'var(--font-geist-sans), sans-serif',
													"--framer-font-size": "38px",
													"--framer-font-weight": "800",
													"--framer-text-color":
														"var(--extracted-r6o4lv, rgb(117, 117, 117))",
												}}
											>
												{labels.items[3].label}
											</motion.p>
										</React.Fragment>
									</RichText></Link>
								)}
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-vMfWh.framer-1qte7ad, .framer-vMfWh .framer-1qte7ad { display: block; }",
	".framer-vMfWh.framer-u8ibv2 { height: 60px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 340px; will-change: var(--framer-will-change-override, transform); }",
	".framer-vMfWh .framer-1jq0t8w { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; left: 0px; overflow: var(--overflow-clip-fallback, clip); padding: 0px 5px 0px 20px; position: absolute; top: 50%; width: 100%; }",
	".framer-vMfWh .framer-8vf0da { height: 20px; position: relative; width: 81px; }",
	".framer-vMfWh .framer-1pjn2jn { height: 13px; left: 22px; position: absolute; top: 0px; width: 60px; }",
	".framer-vMfWh .framer-1f093mb { height: 12px; left: 0px; position: absolute; top: 0px; width: 15px; }",
	".framer-vMfWh .framer-wrd2i4 { height: 2px; left: 3px; position: absolute; top: 8px; width: 9px; }",
	".framer-vMfWh .framer-ovfihq { height: 2px; left: 3px; position: absolute; top: 4px; width: 7px; }",
	".framer-vMfWh .framer-19x0kgg { height: 4px; left: 22px; position: absolute; top: 4px; width: 4px; }",
	".framer-vMfWh .framer-1m8mts6 { height: 12px; left: 15px; position: absolute; top: 0px; width: 17px; }",
	".framer-vMfWh .framer-wh5l4j { height: 13px; left: 32px; position: absolute; top: 0px; width: 14px; }",
	".framer-vMfWh .framer-myzyt2 { height: 13px; left: 46px; position: absolute; top: 0px; width: 14px; }",
	".framer-vMfWh .framer-d9nd6v { height: 6px; left: 22px; position: absolute; top: 14px; width: 34px; }",
	".framer-vMfWh .framer-bvad0v { height: 6px; left: 0px; position: absolute; top: 0px; width: 7px; }",
	".framer-vMfWh .framer-3klohb { height: 2px; left: 2px; position: absolute; top: 2px; width: 4px; }",
	".framer-vMfWh .framer-100rjbg { height: 6px; left: 7px; position: absolute; top: 0px; width: 2px; }",
	".framer-vMfWh .framer-11n219x { height: 6px; left: 10px; position: absolute; top: 0px; width: 7px; }",
	".framer-vMfWh .framer-uv32xz { height: 6px; left: 17px; position: absolute; top: 0px; width: 7px; }",
	".framer-vMfWh .framer-tfu3ql { height: 6px; left: 24px; position: absolute; top: 0px; width: 2px; }",
	".framer-vMfWh .framer-550qyg { height: 6px; left: 27px; position: absolute; top: 0px; width: 7px; }",
	".framer-vMfWh .framer-11goeyg { height: 20px; left: 0px; position: absolute; top: 0px; width: 81px; }",
	".framer-vMfWh .framer-97gq3u { height: 6px; left: 57px; position: absolute; top: 14px; width: 24px; }",
	".framer-vMfWh .framer-1h0xni9 { height: 20px; left: 0px; position: absolute; top: 0px; width: 20px; }",
	".framer-vMfWh .framer-9e6xos { height: 2px; left: 8px; position: absolute; top: 16px; width: 4px; }",
	".framer-vMfWh .framer-1hxk6s1 { height: 5px; left: 13px; position: absolute; top: 10px; width: 5px; }",
	".framer-vMfWh .framer-1gtok4r { height: 5px; left: 3px; position: absolute; top: 10px; width: 5px; }",
	".framer-vMfWh .framer-lugj6d { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 46px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 82px; will-change: var(--framer-will-change-override, transform); }",
	".framer-vMfWh .framer-1iqy00d { flex: none; height: 18px; position: relative; white-space: pre-wrap; width: 55px; word-break: break-word; word-wrap: break-word; }",
	".framer-vMfWh .framer-1ou1rhh { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: center; left: 0px; min-height: 432px; overflow: visible; padding: 0px; position: absolute; top: -72px; width: 100%; }",
	".framer-vMfWh .framer-1ft3hw2, .framer-vMfWh .framer-1tt2cf6, .framer-vMfWh .framer-1ewb01i, .framer-vMfWh .framer-18js542 { flex: none; height: auto; position: relative; white-space: pre; width: auto; transition: --extracted-r6o4lv 0.2s ease; }",
	".framer-vMfWh .framer-1ft3hw2:hover, .framer-vMfWh .framer-1tt2cf6:hover, .framer-vMfWh .framer-1ewb01i:hover, .framer-vMfWh .framer-18js542:hover { --extracted-r6o4lv: rgb(255, 255, 255) !important; }",
	".framer-vMfWh.framer-v-1rfli15.framer-u8ibv2 { height: 470px; }",
	".framer-vMfWh.framer-v-1rfli15 .framer-1jq0t8w { top: 5px; }",
	".framer-vMfWh.framer-v-1rfli15 .framer-1ou1rhh { min-height: unset; top: 86px; }",
	'.framer-vMfWh[data-border="true"]::after, .framer-vMfWh [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FrameraQpj0WMWY = withCSS(Component, css, "framer-vMfWh");
var stdin_default = FrameraQpj0WMWY;
FrameraQpj0WMWY.displayName = "Header";
FrameraQpj0WMWY.defaultProps = {
	height: 60,
	width: 340,
};
addPropertyControls(FrameraQpj0WMWY, {
	variant: {
		options: ["u1JEICRqw", "Z5ukl7fmw"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameraQpj0WMWY,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Funnel Display",
					source: "google",
					style: "normal",
					uiFamilyName: "Funnel Display",
					url: "https://fonts.gstatic.com/s/funneldisplay/v3/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYmmPXXcVwIZDKFA.woff2",
					weight: "400",
				},
				{
					cssFamilyName: "Funnel Display",
					source: "google",
					style: "normal",
					uiFamilyName: "Funnel Display",
					url: "https://fonts.gstatic.com/s/funneldisplay/v3/B50bF7FGv37QNVWgE0ga--4PbZSRJXrOHcLHLoAYGmTXXcVwIZDKFA.woff2",
					weight: "800",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:header
import { WithFramerBreakpoints } from "unframer";

// virtual:__routes
var routes = {
	augiA20Il: {
		path: "/",
	},
};

// virtual:header
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "u1JEICRqw",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e9fcd0079d4f7d103d53614b26096bd76e6f321a5b3cbd1350c20b34fbcc7afc"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				suppressHydrationWarning: true,
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"e9fcd0079d4f7d103d53614b26096bd76e6f321a5b3cbd1350c20b34fbcc7afc"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var header_default = ComponentWithRoot;
export { header_default as default };
